# web 服务访问端口
server:
  port: 8081

spring:
  data:
    # redis
    redis:
      host: "localhost"
      port: 6379
      database: 0
      lettuce:
        pool:
          # 显式开启
          enabled: true
          # 最大连接数 (默认为8)
          max-active: 8
          # 最大空闲连接 (默认为8)
          max-idle: 8
          # 最小空闲连接 (默认为0)
          min-idle: 0
          # 从池中获取连接的最大等待时间 (默认 -1，表示无限等待)
          max-wait: 1000ms
  ai:
    # ollama 配置项
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b